orcid:
  client_id: 0000-0002-2833-9706
  client_secret: 9d7ec9f1-6d5c-49df-abab-4620b6f3e502
  site: http://sandbox-1.orcid.org
  authorize_url: http://sandbox-1.orcid.org/oauth/authorize
  token_url: http://sandbox-1.orcid.org/oauth/token
solr_url: http://search.datacite.org
solr_select: /api
#solr_url: http://localhost:2222
#solr_select: /solr/labs1/select
contact_url: http://datacite.org/contact
mongo_host: 127.0.0.1
mongo_db: crossref
typical_rows: [10, 20, 50, 100, 500]
default_rows: 20
month_short_names: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

