orcid:
  client_id: 0000-0002-3054-1567
  client_secret: 7c2a0c49-dc92-40c1-a12d-441c1fc6f9a0
  site: https://api.orcid.org
  authorize_url: https://orcid.org/oauth/authorize
  token_url: https://api.orcid.org/oauth/token
solr_url: http://5.9.51.2:8983
solr_select: /solr/labs1/select
mongo_host: 127.0.0.1
mongo_db: crossref
typical_rows: [10, 20, 50, 100, 500]
default_rows: 20
month_short_names: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]